name: Qmsg

on:
  workflow_dispatch:

jobs:
  test-qmsg:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      env:
        TZ: Asia/Shanghai
        LANG: zh_CN.UTF-8
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_PASS: ${{ secrets.SECRET_PASS }}
        SECRET_QMSG1: ${{ secrets.SECRET_QMSG1 }}
      run: |
        echo "[info] Checkin Success!" >> tmp
        curl https://qmsg.zendee.cn/send/${SECRET_QMSG1}\
        -d 'msg=${SECRET_ID}$(if [[ $(tail -n 3 tmp) =~ "Success!" ]]; then echo "打卡成功"; else echo "打卡失败"; fi)'
        rm tmp
